spring:
  application:
    name: users-service
  datasource:
    url: ${DB_URL}
    username: events
    password: password
  jpa:
    show-sql: ${DB_SHOW_SQL}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
server:
  port: ${SERVER_PORT:8083}
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
jwt:
  secret: KXiUPknkoVDCHdNrrYnxmA5oQLbv+LE7eHG8vkk71fjEPq0lmlZKwBhUVLUqKSmGam8P4kWxXKTGCDRgpZ5BMA==

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR