spring:

  application:
    name: events-service
  datasource:
      url: ${DB_URL}
      username: events
      password: password
  jpa:
      show-sql: ${DB_SHOW_SQL}
  liquibase:
      change-log: classpath:/db/changelog/db.changelog-master.xml
server:
  port: ${SERVER_PORT:8082}
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
